wandb_version: 1

__cached__setup_devices:
  desc: null
  value:
  - cpu
  - 0
_wandb:
  desc: null
  value:
    cli_version: 0.8.35
    code_path: code/run_glue.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.3
adam_epsilon:
  desc: null
  value: 1.0e-08
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
do_train:
  desc: null
  value: true
evaluate_during_training:
  desc: null
  value: false
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
gradient_accumulation_steps:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 2.0e-05
local_rank:
  desc: null
  value: -1
logging_dir:
  desc: null
  value: null
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 500
max_grad_norm:
  desc: null
  value: 1.0
max_steps:
  desc: null
  value: -1
no_cuda:
  desc: null
  value: false
num_train_epochs:
  desc: null
  value: 3.0
output_dir:
  desc: null
  value: /home/u37216/saved_models/
overwrite_output_dir:
  desc: null
  value: false
per_gpu_eval_batch_size:
  desc: null
  value: 8
per_gpu_train_batch_size:
  desc: null
  value: 32
save_steps:
  desc: null
  value: 500
save_total_limit:
  desc: null
  value: null
seed:
  desc: null
  value: 42
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: null
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
